language: ruby
rvm:
  - 2.7.0

services:
  - mysql

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.17.3'

script:
  - RAILS_ENV=test bundle exec rails db:schema:load db:migrate db:test:prepare --trace
  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml
  - "mysql -e 'create database homebugh_test'"

